GET http://localhost:3001

### Get Items
GET http://localhost:3001/items

### Get an Item by Id
GET http://localhost:3001/items/67e00c2deff3266bb581f2de

### Create an Item
POST http://localhost:3001/items HTTP/1.1
Content-Type: application/json

{
    "productType": "food",
    "productBrand": "French Baker",
    "productName": "Hokkaido Bread",
    "weightPerUnit": "NA",
    "pricePerUnit": "$6.19",
    "sellingPrice": "$7.50",
    "expirationDate": "2025-03-28"
}

### Update an Item
PUT http://localhost:3001/items/67e00c2deff3266bb581f2de HTTP/1.1
Content-Type: application/json

{
    "productType": "food",
    "productBrand": "French Baker",
    "productName": "Hokkaido Bread",
    "weightPerUnit": "NA",
    "pricePerUnit": "$8.19",
    "sellingPrice": "$9.50",
    "expirationDate": "2025-03-28"
}

### Delete an Item
DELETE http://localhost:3001/items/67e00c2deff3266bb581f2de HTTP/1.1